### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by twyrick3** [abjennings/chase-images#2]
Can't get the menu button to appear in the latest version of Firefox.  Reverted firefox back to version 32 and button shows, but nothing happens when it is clicked.

This was a great add-on that I used to track all my business checks.  I'll miss it!

**Comment by abjennings** [comment]
This should be fixed in version 0.17.  They changed the API for adding buttons to the toolbar.  The old one doesn't work anymore.  I have changed to the new one.  You should be able to update from the "add-ons" settings in Mozilla or download the XPI from Github.

**Comment by twyrick3** [comment]
Thank you for looking into this!  I get the button showing v0.17, but whenever I click it I get the message that all images from this page have been downloaded.  But the folder I'm pointing it to is empty and I've tried different folders on different disks.  Any ideas?

**Comment by abjennings** [comment]
Strange.  Did you install from Mozilla.org or download the XPI file from Github?  I just uninstalled it and re-installed it and it's still working fine for me.  I'm on Firefox 42 on Mac.  What FF and OS are you using?

Are you sure that the page you're looking at has some images to download?  If there are no checks in the visible activity list, then it will tell you "All images have been downloaded."  Perhaps if it hasn't downloaded any in the current session, it should say "No images to download."

**Comment by twyrick3** [comment]
I installed the xpi from home and I did the upgrade from Mozilla at my office.  Both acted the same way.  I tried them both on several screens where there were checks visible (and I manually opened and downloaded an image just to be sure it was accessible.

**Comment by twyrick3** [comment]
Update: Did some more testing and I found that it works perfectly on deposits.  Once I noticed that, I set the Chase filter for "Deposits" and I used it to go through a years worth of deposits w/o a hitch.  But still no luck downloading check images.  Tried it on about 20 pages with checks (both filtered on the Chase site and unfiltered).  Perhaps this info will help...thanks!

**Comment by twyrick3** [comment]
Using Version 47.0.2526.73 on Windows 10.

**Comment by twyrick3** [comment]
Using version 42 on Windows 10.

**Comment by abjennings** [comment]
You're right!  Only my deposits were working, not my check images.  It looks like Chase changed something.

I have released a new version (0.18).  Can you try it and let me know?

**Comment by twyrick3** [comment]
This works!...mostly!

Out of a screen with 32 checks on it, it downloaded 30 w/o a problem.  The
ones it skipped over were the ones that have a date after the check
number.  I don't know why Chase puts a date there on a small number of
checks, but your downloader skips over these.  Image attached.

Thanks for taking the time to goof w/this.  It is a perfect utility for me!

**Comment by abjennings** [comment]
Can you try the new version, 0.19?

**Comment by twyrick3** [comment]
This works perfectly!  Thank you so much!  Any way I can donate towards this?
